#!/bin/bash

if ! mount | grep -q cpuset
then
	mkdir -p /dev/cpuset
	mount none /dev/cpuset -t cpuset -o nodev,noexec,nosuid
fi

for i in background system-background top-app foreground camera-daemon
do
    mkdir -p /dev/cpuset/$i
    echo 0 > /dev/cpuset/$i/mems
done

echo 0-2 > /dev/cpuset/background/cpus
echo 0-5 > /dev/cpuset/system-background/cpus

for i in top-app foreground camera-daemon
do
    echo 0-7 > /dev/cpuset/$i/cpus
done

# Not really related to CPUSET but since we are certain this runs only on Android device...
# We do not need wakeup sources as the system never sleeps, only idles.
find /sys/devices -name wakeup | while read file
do
	if echo $file | grep -q 'power/wakeup'
	then
		echo disabled > $file
	fi
done

exit 0
